# -*- coding: utf-8 -*-
"""One-off script: execute EDA_PLAN.md's checklist for real against
methodology/full_run/ranked_full.csv (34,766 rows). Writes
methodology/EDA_REPORT.md and plot PNGs under methodology/full_run/plots/.
Not part of the reusable methodology/scripts/ library -- a single-run
analysis script, kept here for reproducibility.
"""
import os
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
FULL_RUN = os.path.join(ROOT, "methodology", "full_run")
PLOTS = os.path.join(FULL_RUN, "plots")
os.makedirs(PLOTS, exist_ok=True)

df = pd.read_csv(os.path.join(FULL_RUN, "ranked_full.csv"), encoding="utf-8")
raw = pd.read_csv(os.path.join(ROOT, "AstanaLinksParserJune2026_parsed.csv"), encoding="utf-8")
n = len(df)

out = []
def p(*a):
    out.append(" ".join(str(x) for x in a))

p("# EDA_REPORT.md — Real Exploratory Analysis (Full Dataset, n=%d)" % n)
p()
p("Generated by running the `EDA_PLAN.md` checklist for real against")
p(f"`methodology/full_run/ranked_full.csv` — the full")
p(f"`AstanaLinksParserJune2026_parsed.csv` dataset (34,766 raw rows, {n}")
p("after dropping duplicate/relisted units), parsed/featured/ranked")
p("end to end. This is the first REAL (non-sample, non-illustrative) EDA")
p("this project has produced; contrast with the earlier 16-row")
p("`methodology/samples/SAMPLE_EDA_REPORT.md`, which was illustrative only.")
p()

# 1. Missingness
p("## 1. Missingness report")
p()
fields = ["price_tenge","district","building_type","complex_name","build_year",
          "floor","floor_total","area_total_m2","kitchen_area_m2",
          "apartment_condition","ceiling_height_m","bathroom","balcony",
          "balcony_glazed","parking","former_dormitory","exchange_possible","rooms"]
rows = []
for f in fields:
    if f == "apartment_condition":
        present = (df[f] != "unknown").sum()
    else:
        present = df[f].notna().sum()
    rows.append((f, present, n-present, f"{present/n:.1%}"))
miss_df = pd.DataFrame(rows, columns=["field","present","missing","coverage"])
p(miss_df.to_string(index=False))
p()

# 2. Distributions
p("## 2. Distribution checks")
p()
for c in ["price_tenge","area_total_m2","price_m2","build_year"]:
    s = df[c].dropna()
    p(f"- **{c}**: n={len(s)}, min={s.min():,.0f}, p25={s.quantile(.25):,.0f}, "
      f"median={s.median():,.0f}, mean={s.mean():,.0f}, p75={s.quantile(.75):,.0f}, "
      f"max={s.max():,.0f}, std={s.std():,.0f}")
p()

# build_year sanity bounds
current_year = 2026
suspect_old = df[df["build_year"] < 1950]
suspect_future = df[df["build_year"] > current_year + 5]
p(f"- build_year < 1950 (suspect): {len(suspect_old)} rows")
p(f"- build_year > {current_year+5} (suspect): {len(suspect_future)} rows")
p()

# listings per district
p("### Listings per district")
p(df["district"].value_counts(dropna=False).to_string())
p()

# listings per complex - top 20 + long tail
p("### Listings per complex (top 20)")
complex_counts = df["complex_name"].value_counts()
p(complex_counts.head(20).to_string())
p()
p(f"Total distinct complexes: {complex_counts.shape[0]}")
p(f"Complexes with exactly 1 listing: {(complex_counts == 1).sum()} "
  f"({(complex_counts==1).sum()/complex_counts.shape[0]:.1%} of complexes)")
p(f"Complexes with >= 5 listings (meets FEATURE_SPEC.md min_n): {(complex_counts >= 5).sum()}")
p(f"Listings in a complex with >= 5 listings: {complex_counts[complex_counts>=5].sum()} "
  f"({complex_counts[complex_counts>=5].sum()/n:.1%} of all listings)")
p()

# Plots
fig, ax = plt.subplots(figsize=(7,4))
df["price_m2"].dropna().pipe(lambda s: ax.hist(np.log10(s), bins=60, color="#4C72B0"))
ax.set_xlabel("log10(price_m2)")
ax.set_title("price_m2 distribution (log10 scale), n=%d" % df["price_m2"].notna().sum())
fig.tight_layout()
fig.savefig(os.path.join(PLOTS, "price_m2_hist_log.png"), dpi=110)
plt.close(fig)

fig, ax = plt.subplots(figsize=(7,4))
df["area_total_m2"].dropna().pipe(lambda s: ax.hist(s.clip(upper=250), bins=60, color="#55A868"))
ax.set_xlabel("area_total_m2 (clipped at 250)")
ax.set_title("area distribution")
fig.tight_layout()
fig.savefig(os.path.join(PLOTS, "area_hist.png"), dpi=110)
plt.close(fig)

fig, ax = plt.subplots(figsize=(8,4))
dc = df["district"].value_counts()
ax.bar(dc.index.astype(str), dc.values, color="#C44E52")
ax.set_ylabel("listings"); ax.set_title("Listings per district")
plt.xticks(rotation=45, ha="right")
fig.tight_layout()
fig.savefig(os.path.join(PLOTS, "district_counts.png"), dpi=110)
plt.close(fig)

p("Plots saved: methodology/full_run/plots/price_m2_hist_log.png, area_hist.png, district_counts.png")
p()

# 3. Outlier detection
p("## 3. Outlier detection (district-relative IQR + district_median*[0.2,5] rule)")
p()
outlier_total = 0
for dist, grp in df.dropna(subset=["price_m2","district"]).groupby("district"):
    if len(grp) < 10:
        p(f"- {dist}: n={len(grp)} (too small for a stable in-group IQR, skipped)")
        continue
    q1, q3 = grp["price_m2"].quantile([.25,.75])
    iqr = q3-q1
    lo, hi = q1-1.5*iqr, q3+1.5*iqr
    flagged = grp[(grp["price_m2"]<lo)|(grp["price_m2"]>hi)]
    outlier_total += len(flagged)
    p(f"- {dist}: n={len(grp)}, IQR bounds=({lo:,.0f}, {hi:,.0f}), outliers={len(flagged)} ({len(flagged)/len(grp):.1%})")
p(f"\nTotal IQR-flagged outliers across districts: {outlier_total}/{df['price_m2'].notna().sum()} "
  f"({outlier_total/df['price_m2'].notna().sum():.1%})")
p()

sane = df.dropna(subset=["price_m2","district_median_price_m2"])
bad = sane[(sane["price_m2"] < 0.2*sane["district_median_price_m2"]) |
           (sane["price_m2"] > 5*sane["district_median_price_m2"])]
p(f"Global sanity rule (price_m2 outside district_median*[0.2,5]): "
  f"{len(bad)}/{len(sane)} ({len(bad)/len(sane):.2%})")
p()

malformed = df[(df["price_tenge"].notna()) & ((df["price_tenge"] <= 0) | (df["price_tenge"] < 1_000_000))]
p(f"Malformed prices (<=0 or < 1,000,000 tenge): {len(malformed)}")
p()

# 4. Duplicate / relist detection
p("## 4. Duplicate / relist detection")
p()
dup_key = df.dropna(subset=["lat","lon","area_total_m2","price_tenge"])
dups = dup_key[dup_key.duplicated(subset=["lat","lon","area_total_m2","price_tenge"], keep=False)]
n_dup_groups = dup_key[dup_key.duplicated(subset=["lat","lon","area_total_m2","price_tenge"], keep="first")].shape[0]
p(f"Rows checked (post-dedup): {len(dup_key)}")
p(f"Rows that are part of a duplicate (lat,lon,area,price) group: {len(dups)}")
p(f"Distinct extra-copy count (groups minus 1 each): {n_dup_groups}")
p(f"(Expected 0 here -- {34766 - n} rows were already dropped for this exact reason "
  f"in feature_engineering.py's engineer_features(), per the user's decision to drop "
  f"rather than merely flag relisted units. This section re-checks post-dedup as a "
  f"regression guard.)")
p()
# Known literal duplicate raw rows (exact source_row+url+status=error dupes)
raw_dup_urls = raw[raw.duplicated(subset=["source_row"], keep=False)]
p(f"Separately: {len(raw_dup_urls)} rows in the raw scraped CSV share a duplicated "
  f"source_row (5 URLs appear twice each, both times status=error -- a LinksParser "
  f"resume/retry artifact, not a parsing issue; already deduped at the join step in "
  f"feature_engineering.py, before the relist-dedup above runs).")
p()

# 5. Geographic sanity check
p("## 5. Geographic sanity check (Astana bounding box lat [51.0,51.25], lon [71.30,71.55])")
p()
geo = df.dropna(subset=["lat","lon"])
oob = geo[(geo["lat"]<51.0)|(geo["lat"]>51.25)|(geo["lon"]<71.30)|(geo["lon"]>71.55)]
p(f"Rows with coords: {len(geo)}/{n}")
p(f"Outside bounding box: {len(oob)} ({len(oob)/len(geo):.2%})")
if len(oob):
    p(oob[["url","lat","lon"]].head(10).to_string(index=False))
p()

# 6. Correlation matrix (VIF already done in ranking_full_report.txt)
p("## 6. Correlation matrix across engineered numeric features")
p()
num_cols = ["ln_price_m2","ln_area","building_age","ceiling_height_m",
            "distance_to_center_km","avg_price_m2_within_3km_median",
            "n_neighbors_3km","complex_median_price_m2","district_median_price_m2"]
corr = df[num_cols].corr(numeric_only=True)
p(corr.round(2).to_string())
p()
p("(Full VIF-per-continuous-predictor check already run for real in "
  "`methodology/full_run/ranking_full_report.txt` — all VIFs came back "
  "1.00-1.28, well under the >10 multicollinearity threshold; the a priori "
  "worry in RANKING_METHODOLOGY.md section 6 that distance_to_center_km "
  "and avg_price_m2_within_3km_median would be collinear did NOT "
  "materialize in the real data.)")
p()

# 7. Full-scale audits
p("## 7. Full-scale audits")
p()
p("### Distinct district strings")
p(df["district"].value_counts(dropna=False).to_string())
p()
p("### Distinct building_type strings")
p(df["building_type"].value_counts(dropna=False).to_string())
p()
n_pipe = raw.shape[0]  # placeholder, real count from parse report
p("Pipe-delimited parameters fallback frequency and under-construction "
  "frequency are already reported in `methodology/full_run/parse_full_report.txt` "
  "(1,659/34,766 = 4.8% pipe-fallback) and are re-derivable per-row from "
  "`is_under_construction` in `parsed_full.csv`.")
uc = pd.read_csv(os.path.join(FULL_RUN, "parsed_full.csv"), encoding="utf-8")
n_uc = (uc["is_under_construction"] == True).sum()
p(f"is_under_construction=True (re-derived per-row, using each row's own fetched_at year): "
  f"{n_uc}/{n} ({n_uc/n:.1%})")
p()

report_path = os.path.join(ROOT, "methodology", "EDA_REPORT.md")
with open(report_path, "w", encoding="utf-8") as f:
    f.write("\n".join(out) + "\n")
print("wrote", report_path)
print(len("\n".join(out)), "chars")
